[settings]
auto_install = true
legacy_version_file = true
not_found_system_fallback = true
dotfiles.root = "~/Projects/dots"

[bootstrap.repos]
"~/Projects/nvim" = { url = "https://github.com/remoterabbit/nvim", ref = "main" }
"~/Projects/dots" = { url = "https://github.com/remoterabbit/dots", ref = "main" }

[dotfiles]
"~/.config/nvim" = { source = "~/Projects/nvim", mode = "symlink"}
"~/.dots" = "~/Projects/dots"
"~/.config/mise/config.toml" = "~/Projects/dots/config.toml"
